permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "Sweeter Candy Co."
  description: |
    Online candy company for candy lovers with a sweet tooth.
  font_url: "https://use.typekit.net/zaf4ypz.css"
  colors:
    background: "--color-primary-extralight"
    accent: "--color-white"
    patterns:
      brand.logos: "--color-white"
      buttons.basic: "--color-white"
      buttons.ghost: "--color-white"
      buttons.light: "--color-white"
  rationales:
    typefaces.primary: |
      Urbane was chosen because it's a sans-serif that's modern but still playful, which goes with the theme of the site. It is used in all body copy and any h2s and below.
    typefaces.secondary: |
      Bello-Pro is only used for h1s specifically. It is used to create emphasis on the main headers of each page while tying in the font from the logo.
    colors.primary: |
      The primary colour used is the main colour of the gradient that appears on every page of the website. This colour was chosen because it's a vibrant coral/pink that represents the sweetness and colourfulness of candy.
    colors.accent: |
      The accent colours are contrasting colours to the primary pink colour. This is so that the colour and vibrant colour scheme is still followed, by it is still easy to distinguish the contrast between the primary and accent colours.
