title: "Cards"
description: |
 Website cards are a way to display important information; such as displaying products, or distinguishing certain sections within a website.
patterns:
  product-card:
    title: "Product Card"
    description: |
      This card displays the general overview of a product, these cards should be placed in the shop page.
  product-details:
    title: "Product Details"
    description: |
      These cards are used once a user clicks a product card. This card takes the user to another page to display more details on the product they just selected. Here the user can add the product to their cart.
